[build]
  publish = "."

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/history"
  to = "/history.html"
  status = 200

[[redirects]]
  from = "/result"
  to = "/result.html"
  status = 200

[[redirects]]
  from = "/community"
  to = "/community.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/test"
  to = "/test.html"
  status = 200
